#Minecraft server for Smudger
#cd ~/Documents/GitHub/DockerConfigs; git pull;
#cp ~/Documents/GitHub/DockerConfigs/Smudger/minecraft-paper.yml ~/Documents/GitHub/docker-compose.yml
#cd ~/docker; docker-compose up d
#docker logs minecraft
---
version: "2"
services:
  minecraft-server:
    image: itzg/minecraft-server:multiarch-latest
    container_name: minecraft
    environment:
      - EULA=TRUE
      - VERSION=1.17.1 #LATEST is supported but Paper version may lag behind so hardcode this
      - MEMORY=2G #"1G" by default, can be used to adjust both initial (Xms) and max (Xmx) memory heap settings of the JVM
      - INIT_MEMORY=1G #independently sets the initial heap size
      - MAX_MEMORY=2G #independently sets the max heap size
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - TYPE=PAPER
      - TZ=America/New_York
    ports:
      - 25565:25565
    volumes:
      - /Users/steve/docker/config/minecraft/ServerJEPaper:/data
    restart: unless-stopped