#Minecraft server for Smudger
#cd ~/Documents/GitHub/DockerConfigs; git pull;
#cp ~/Documents/GitHub/DockerConfigs/Smudger/minecraft-paper.yml ~/Documents/GitHub/docker-compose.yml
#cd ~/docker; docker-compose up d
#docker logs minecraft
---
version: "2"
services:
  minecraft-server:
    image: itzg/minecraft-server:multiarch
    container_name: minecraft
    environment:
      - EULA=TRUE
      - VERSION=1.16.5 #LATEST is supported but Paper version may lag behind so hardcode this
      - MEMORY=2G
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - TYPE=PAPER
    ports:
      - 25565:25565
    volumes:
      - /Users/steve/docker/config/minecraft/ServerJEPaper:/data
    restart: unless-stopped