#Minecraft server for Smudger
---
version: "2"
services:
  minecraft-server:
    image: itzg/minecraft-server:multiarch
    container_name: minecraft
    network_mode: host
    environment:
      - PUID=998
      - PGID=100
      - EULA=TRUE
      - VERSION=1.16.5 #LATEST is supported but Paper version may lag behind so hardcode this
      - MEMORY=2G
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - TYPE=PAPER
    ports:
      - 25565:25565
    volumes:
      - ~/docker/minecraft/ServerJEPaper:/data
    restart: unless-stopped