#This is untested and still theoretical!
#Example: https://github.com/kylemanna/docker-openvpn/blob/e83f0118e02a897cd001ac819608efd4144795ad/docs/docker-compose.md
---
version: "2.1"
services:
  openvpn:
    image: giggio/openvpn-arm
    container_name: openvpn
    restart: unless-stopped
    environment:
      - DEBUG=0
    volumes:
      - /etc/config/openvpn-data:/etc/openvpn
    ports:
        - "1194:1194/udp"
    cap_add:
        - NET_ADMIN
    user: udp://4lanc.duckdns.org