#default login admin/admin
version: "2.1"
services:

  filebrowser:
    image: filebrowser/filebrowser:pi
    volumes:
        - /srv/dev-disk-by-label-EVO256:/srv
        - /etc/config/filebrowser:/config
        - /etc/config/filebrowser/filebrowser.db:/config/filebrowser/database.db
        - /etc/config/filebrowser/filebrowser.json:/config/filebrowser/filebrowser.json
    ports:
        - 8407:80
    restart: unless-stopped