---
version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
       - PUID=998
       - PGID=100
       - VERSION=docker
    volumes:
       - /etc/config/plex:/config
       - /srv/dev-disk-by-label-EVO256/Photos:/Photos
       - /srv/dev-disk-by-label-EVO256/Videos:/Videos