#https://hub.docker.com/r/kerberos/kerberos/tags
#https://github.com/kerberos-io/kerberos-docker
#https://github.com/kerberos-io/kerberos-docker/issues/14
#"By default the images captured are saved to /etc/opt/kerberosio/capture/"
#Tested/working
---
version: "2"
services:
  kerberos:
    image: kerberos/kerberos:latest
    container_name: kerberos
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /dockerconfig/kerberos/capture:/etc/opt/kerberosio/capture
      - /dockerconfig/kerberos/config:/etc/opt/kerberosio/config
      - /dockerconfig/kerberos/logs:/etc/opt/kerberosio/logs
      - /dockerconfig/kerberos/webconfig:/var/www/web/config
    ports:
      - 8080:80 #WebUI
      - 8889:8889 #kerberos comm port
    devices:
       - "/dev/vchiq:/dev/vchiq"
    privileged: true
    restart: unless-stopped