#Airsonic-Advanced is a more modern implementation of the Airsonic fork,
#with several key performance and feature enhancements.
#It adds and supersedes several features in Airsonic.
#https://github.com/airsonic-advanced/airsonic-advanced
#https://hub.docker.com/r/airsonicadvanced/airsonic-advanced
#Please note that for Docker images, the volume mounting points have changed and are different from Airsonic.
#Airsonic mount points are at /airsonic/* inside the container. 
#Tested/working
---
version: "2.1"
services:
  airsonic-advanced:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic-advanced
    volumes:
      - /srv/dev-disk-by-label-Data/config/airsonic-advanced:/var/airsonic
      - /srv/dev-disk-by-label-Data/Audio/Music:/var/music:rw
      - /srv/dev-disk-by-label-Data/Audio/Music/Playlists/Airsonic:/var/playlists:rw
      - /srv/dev-disk-by-label-Data/Audio/Podcasts/airsonic:/var/podcasts:rw
    ports:
      - 4041:4041/tcp
    restart: unless-stopped