#Clone Hero server
#https://hub.docker.com/r/corysanin/clone-hero-server
#https://gitlab.com/CorySanin/clone-hero-server-docker
#Untested
---
version: "2.1"
services:
  cloneheroserver:
    image: corysanin/clone-hero-server:latest
    container_name: cloneheroserver
    volumes:
      - /srv/dev-disk-by-label-Data/config/cloneheroserver:/usr/src/config
      #- /srv/dev-disk-by-label-Data/Public:/downloads
    ports:
      - 14242:14242/udp
    restart: unless-stopped