#Cloud Commander is an orthodox web file manager with console and editor.
#https://github.com/coderaiser/cloudcmd
#https://hub.docker.com/r/coderaiser/cloudcmd
#https://dbtechreviews.com/2020/03/how-to-install-cloud-commander-in-openmediavault-5-with-docker-and-portainer/
#tested/working
---
version: "2.1"
services:
  cloudcmd:
    image: coderaiser/cloudcmd:latest
    ports:
      - 7000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
      - /srv/dev-disk-by-label-Data/Public:/srv/dev-disk-by-label-Data/Public
      - /srv/dev-disk-by-label-Data/Audio:/srv/dev-disk-by-label-Data/Audio
      - /srv/dev-disk-by-label-Data/Photos:/srv/dev-disk-by-label-Data/Photos
      - /srv/dev-disk-by-label-Data/Videos:/srv/dev-disk-by-label-Data/Videos
      - /srv/dev-disk-by-label-Data/OfflineDocs:/srv/dev-disk-by-label-Data/OfflineDocs
      - /srv/dev-disk-by-label-Data/OSes:/srv/dev-disk-by-label-Data/OSes
      - /srv/dev-disk-by-label-Data/Progs:/srv/dev-disk-by-label-Data/Progs
      - /srv/dev-disk-by-label-Data/Test:/srv/dev-disk-by-label-Data/Test
      - /srv/dev-disk-by-label-WD12TB/ArchiveSteve:/srv/dev-disk-by-label-WD12TB/ArchiveSteve
      - /srv/dev-disk-by-label-EVO8601TB/General1TB:/srv/dev-disk-by-label-EVO8601TB/General1TB
    restart: unless-stopped