#https://github.com/linuxserver/docker-code-server
#https://docs.linuxserver.io/images/docker-code-server
#Visual Studio Code server
#Tested/working, you can use the "latest" tag but it unnecessarily pulls unrelated images, so for the Pi we'll use arm32v7-latest.
#Extra volumes may be mounted to access/save files.
---
version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server:arm32v7-latest
    container_name: code-server
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
      #- PASSWORD=password #Optional web gui password, if not provided, there will be no auth.
      - SUDO_PASSWORD=password #If this optional variable is set, user will have sudo access in the code-server terminal with the specified password.
      #- SUDO_PASSWROD_HASH=aal;kjsdlk;ajsd #Optionally set sudo password via hash (takes priority over SUDO_PASSWORD var). Format is $type$salt$hashed.
      #- PROXY_DOMAIN=code-server.my.domain #If this optional variable is set, this domain will be proxied for subdomain proxying. See Documentation​
    volumes:
      - /srv/dev-disk-by-label-Data/config/code-server:/config
      - /srv/dev-disk-by-label-Data/Public:/public
      - /srv/dev-disk-by-label-Data/OfflineDocs:/offlinedocs
    ports:
      - 8443:8443
    restart: unless-stopped