#https://github.com/linuxserver/docker-doublecommander
#Double Commander is a free cross platform open source file manager with two panels side by side.
#It is inspired by Total Commander and features some new ideas.
#Tested/working, though I'm not sure what this'd be good for.
---
version: "2.1"
services:
  doublecommander:
    image: ghcr.io/linuxserver/doublecommander:latest
    container_name: doublecommander
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /srv/dev-disk-by-label-Data/config/doublecommander:/config
      - /srv/dev-disk-by-label-Data/Public:/data #Host data directories, mount as many as needed.
    ports:
      - 3000:3000
    restart: unless-stopped