#default login admin/admin
#https://hub.docker.com/r/filebrowser/filebrowser/tags
#https://github.com/filebrowser/filebrowser/
version: "2.1"
services:
  filebrowser:
    image: filebrowser/filebrowser:pi
    volumes:
        - /srv/dev-disk-by-label-Data:/srv
        - /srv/dev-disk-by-label-Data/config/filebrowser:/config
        - /srv/dev-disk-by-label-Data/config/filebrowser/filebrowser.db:/config/filebrowser/database.db
        - /srv/dev-disk-by-label-Data/config/filebrowser/filebrowser.json:/config/filebrowser/filebrowser.json
    ports:
        - 8407:80
    restart: unless-stopped