#Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media.
#It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps.
#Jellyfin is descended from Emby's 3.5.2 release and ported to the .NET Core framework to enable full cross-platform support.
#There are no strings attached, no premium licenses or features, and no hidden agendas: just a team who want to build something better and work together to achieve it.
#https://github.com/linuxserver/docker-jellyfin
#Untested
---
version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
    ports:
      - 8096:8096
      #- 8920:8920/udp #optional
      #- 1900:1900/udp #optional
    volumes:
      - /srv/dev-disk-by-label-Data/config/jellyfin:/config
      - /srv/dev-disk-by-label-Data/Videos/All\ Other\ Videos/TV\ Shows:/data/tvshows
      - /srv/dev-disk-by-label-Data/Videos/All\ Other\ Videos/Movies:/data/movies
      #- /srv/dev-disk-by-label-Data/Photos:/Photos
      #- /srv/dev-disk-by-label-Data/Audio:/Audio
    restart: unless-stopped