
#https://hub.docker.com/r/pihole/pihole
#https://github.com/pi-hole/docker-pi-hole
#https://docs.pi-hole.net/
#https://old.reddit.com/r/portainer/comments/i11hxo/why_does_this_stack_not_propagate_the_env_vars/
#https://github.com/petersem/DockerStack/blob/master/docker-compose.yaml
#Recommended but not required (DHCP needs NET_ADMIN)
#https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#Untested!
---
version: "2.1"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "6767:67/udp"
      - "9999:80/tcp"
      - "4443:443/tcp"
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
      - WEBPASSWORD=somethingreallytemporary
      - ServerIP=10.0.0.7
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1
      - TEMPERATUREUNIT=f
      - FTL_CMD=debug
      - DNSMASQ_LISTENING=all
    volumes:
       - '/srv/dev-disk-by-label-Data/config/pihole/config:/etc/pihole/'
       - '/srv/dev-disk-by-label-Data/config/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d'