#https://hub.docker.com/r/laurentsev/podcast-rss
#Not working yet. Port mappings aren't cooperating.
version: "2"
services:
  podcast-rss:
    container_name: podcast-rss
    image: laurentsev/podcast-rss:arm32latest
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: 998
      PGID: 100
      PODCAST_FS_HOME: /podcast
      ROOT_URL: http://myserver:8081/
    volumes:
      - /srv/dev-disk-by-label-Data/config/podcast:/podcast
    ports:
      - 8081:8081