#ich777/thunderbird
#https://hub.docker.com/r/ich777/thunderbird
#https://github.com/ich777/docker-thunderbird
#Support Thread: https://forums.unraid.net/topic/83786-support-ich777-application-dockers/
#The container will check on every restart if there is a newer version available.
#RESOLUTION: You can also change the resolution from the WebGUI,
#to do that simply click on 'Show more settings...'
#(on a resolution change it can occour that the screen is not filled entirely with the Thunderbird window, simply restart the container and it will be fullscreen again).
#Webgui address: http://[SERVERIP]:[PORT]/vnc_auto.html
#Example: http://10.0.0.7/8099/vnc_auto.html
#Tested/working, but laggy. Restart container if first run is unusable.
---
version: "2.1"
services:
  thunderbird:
    image: ich777/thunderbird:latest
    container_name: thunderbird
    environment:
      - PUID=998 #User identifier
      - PGID=100 #Group identifier
      - UMASK=000 #Umask value
      - CUSTOM_RES_W=1280 #preferred screen width
      - CUSTOM_RES_H=768 #preferred screen height
      - THUNDERBIRD_LANG=en-US #preferred Thunderbird language
      - THUNDERBIRD_V=latest #Enter your preferred Thunderbird version or 'latest' to install the latest version
      - DATA_PERM=770 #Data permissions for /thunderbird folder
      - DATA_DIR=/thunderbird #Folder for Thunderbird
    ports:
      - 8099:8080
      #- 8080:8080
    volumes:
      - /srv/dev-disk-by-label-Data/config/thunderbird:/thunderbird
      #- /mnt/cache/appdata/thunderbird:/thunderbird
    restart: unless-stopped