#https://github.com/Tzahi12345/YoutubeDL-Material
#https://hub.docker.com/r/tzahi12345/youtubedl-material/
#Use this for proxies to get around youtube bans/throttling: https://spys.one/en/socks-proxy-list/
#tested/working
version: "2"
services:
    ytdl_material:
        image: tzahi12345/youtubedl-material:nightly-arm
        environment:
            #UID: '998' #These broke the container (regardless of quotations) so I'm leaving them commented out
            #GID: '100' #These broke the container (regardless of quotations) so I'm leaving them commented out
            ALLOW_CONFIG_MUTATIONS: 'true'
            #HTTP_PROXY: "socks://207.97.174.134:1080" #https://github.com/Tzahi12345/YoutubeDL-Material/issues/177#issuecomment-722685712
            #HTTPS_PROXY: "socks://207.97.174.134:1080" #https://github.com/Tzahi12345/YoutubeDL-Material/issues/177#issuecomment-722685712
            #FTP_PROXY: "socks://207.97.174.134:1080" #https://github.com/Tzahi12345/YoutubeDL-Material/issues/177#issuecomment-722685712
        restart: unless-stopped
        volumes:
            - /srv/dev-disk-by-label-Data/config/ytdl:/app/appdata
            - /srv/dev-disk-by-label-Data/Public/ytdl/audio:/app/audio
            - /srv/dev-disk-by-label-Data/Public/ytdl/video:/app/video
            - /srv/dev-disk-by-label-Data/Public/ytdl/subscriptions:/app/subscriptions
            - /srv/dev-disk-by-label-Data/Public/ytdl/users:/app/users
        ports:
            - "9877:17442"