#Works
#https://github.com/wiserain/youtube-dl-server
#http://host:port/youtube-dl/
version: "2"

services:
  ytb-dl:
    container_name: ytb-dl
    image: wiserain/youtube-dl-server:latest
    restart: unless-stopped
    network_mode: host
    ports:
      #- ${PORT_TO_EXPOSE}:8080
      - 9876:9876
    volumes:
      - /srv/dev-disk-by-label-Data/Public/youtube-dl:/youtube-dl
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
      - YTBDL_O=%(title)s - [%(id)s].%(ext)s
      - YTBDL_F=bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]
      - YTBDL_SERVER_PORT=9876
      - YTBDL_VER=latest
      - YTBDL_SERVER_ROOT=/youtube-dl